version: '3'

services:
  node_js:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    image: higordockers/node:prod
    container_name: node
    restart: on-failure
    tty: true
    networks:
      - nodenginx
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    # para não perder os dados do mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenginx
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: higordockers/nginx:prod
    container_name: nginx
    tty: true
    networks:
      - nodenginx
    ports:
      - "8080:80"
    depends_on:
      - node_js

networks:
  nodenginx:
    driver: bridge